apiVersion: v1
kind: Namespace
metadata:
  name: target-system
  labels:
    environment: development
    part-of: aiops-platform
---
apiVersion: v1
kind: Namespace
metadata:
  name: aiops
  labels:
    environment: development
    part-of: aiops-platform
---
apiVersion: v1
kind: Namespace
metadata:
  name: observability
  labels:
    environment: development
    part-of: aiops-platform
---
apiVersion: v1
kind: Namespace
metadata:
  name: memory
  labels:
    environment: development
    part-of: aiops-platform
---
apiVersion: v1
kind: Namespace
metadata:
  name: chaos
  labels:
    environment: development
    part-of: aiops-platform
---
apiVersion: v1
kind: Namespace
metadata:
  name: sandbox
  labels:
    environment: development
    part-of: aiops-platform
